import { Component } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { Title } from '@angular/platform-browser';
import { ActivatedRoute, Router } from '@angular/router';
import { takeWhile, catchError, of } from 'rxjs';

import { MsgboxService } from '@app/shared/msgbox';
import { DefinitionsService, IDefinition } from '@app/core/definitions';

@Component({
  selector: 'app-definition-edit',
  templateUrl: './definition-edit.component.html',
  styleUrls: ['./definition-edit.component.scss']
})
export class DefinitionEditComponent {

  public record?: IDefinition;
  public loading: boolean;
  public errorFromBackendOnLoad?: string;
  public errorFromBackendOnSave?: string;

  public editForm: FormGroup;
  public frmOpenApiRemote: FormGroup;
  public frmOpenApiText: FormGroup;
  public working: boolean;

  private destroyed: boolean;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private service: DefinitionsService,
    private msgbox: MsgboxService,
    public title: Title
  ) {

    this.loading = true;

    this.editForm = new FormGroup(
      {
        name: new FormControl('', Validators.required),
        value: new FormControl(''),
      });
  }

  public ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.service
        .getDefinitionById(id)
        .pipe(
          takeWhile(() => !this.destroyed),
          catchError((response) => {
            this.loading = false;
            if (response.status !== 404) {
              this.errorFromBackendOnLoad =
                response.error?.message ||
                'Something went wrong in loading your definition. Please try again later.';
            }

            return of(null);
          })
        )
        .subscribe((data) => {
          if (data) {
            this.record = data;
            this.loading = false;

            this.editForm.patchValue({
              ...this.record
            });

            this.title.setTitle(`Service Directory — Edit definition`);
            this.errorFromBackendOnLoad = null;
          }
        });
    } else {
      this.loading = false;
      this.title.setTitle(`Service Directory — Create definition`);
    }
  }

  public shouldShowErrorFor(fieldName: string, errorName?: string): boolean {
    return (
      this.editForm.get(fieldName).touched &&
      (errorName
        ? this.editForm.get(fieldName).errors?.[errorName]
        : !this.editForm.get(fieldName).valid)
    );
  }

  public submitThenRedirect(redirectPath?: string) {
    this.errorFromBackendOnSave = null;

    if (!this.editForm.valid) {
      // Validation error-messages only appear if a control has been touched.
      this.editForm.markAllAsTouched();
      return;
    }

    const request = {
      ...this.record || {},
      ...this.editForm.value
    };

    this.working = true;

    const op = request.id
      ? this.service.updateDefinition(request)
      : this.service.createDefinition(request);

    op.pipe(
      takeWhile(() => !this.destroyed),
      catchError((response) => {
        this.working = false;
        this.errorFromBackendOnSave =
          response.error?.error ||
          'Something went wrong in saving your definition. Please check the information is correct, or try again later.';

        return of(null);
      })
    ).subscribe((savedRecord: IDefinition) => {

      this.working = false;

      if (savedRecord) {
        // _id is generated by the back-end if we’re adding a new service,
        // so it’s safe to navigate to it once we’ve created the service.
        this.router.navigateByUrl(redirectPath ?? '/definitions');
        this.msgbox.showSuccess('Operation completed successfully');
      }
    });
  }

  public ngOnDestroy(): void {
    this.destroyed = true;
  }

}
