# Replace "exampledomain" with the organisation-specific domain.

servicedirectory:
  config:
    API_ENDPOINT: "https://servicedirectoryapi.exampledomain.com"

servicedirectoryapi:
  config:
    # Authentication
    SECURITY_ENABLED: 'false'

    # Service Directory API
    PORT: "3002"
    SERVER: "https://servicedirectoryapi.exampledomain.com"

    # Objects Repository
    REPOSITORY_API_URL: "https://dlmstorebackend.idta.ds2.icelab.cloud/repository-api"
    REPOSITORY_OWNER_ID: "service-directory"
    REPOSITORY_API_KEY: ""
