stages:
  - publish

publish:
  image: docker:dind
  stage: publish
  tags:
  - wasp-service-directory-api
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY/$CI_PROJECT_PATH
  - docker build . -t $CI_REGISTRY/$CI_PROJECT_PATH/$CI_REGISTRY_IMAGE
  - docker push $CI_REGISTRY/$CI_PROJECT_PATH/$CI_REGISTRY_IMAGE